# Generated by Django 4.2.4 on 2023-08-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_rename_sale_product_price_sale_product_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preview',
            new_name='views',
        ),
    ]
