# Generated by Django 4.2.4 on 2023-08-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0003_rename_preview_product_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CarProduct',
            new_name='CartProduct',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_value',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='car',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car',
            new_name='cart',
        ),
    ]
