# Generated by Django 4.2.4 on 2023-08-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0004_rename_car_cart_rename_carproduct_cartproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name_complete',
            new_name='full_name',
        ),
    ]
